server:
  port: 10000
spring:
  data:
    mongodb:
      uri: mongodb://106.12.90.33:27017/graduation



lin-chen:
  token-verify:
    verifyURL:
      - GET /admin/**
      - PUT /admin/**
      - DELETE /admin/**


      - PUT /api/user/**


