server:
  port: 10000
spring:
  data:
    mongodb:
      uri: mongodb://106.12.90.33:27017/graduation



lin-chen:
  token-verify:
    verifyURL:
      - GET /admin/**
      - PUT /admin/**
      - DELETE /admin/**

      - POST /api/topics/**

      - GET /api/user/**
      - POST /api/user/info
      - PUT /api/user/**
      - DELETE /api/user/**

      - POST /api/comments/**
      - GET /api/comments/one
      - GET /api/comments/me


